version: 1.0.{build}

branches:
  only:
    - master
    - dev

cache:
  - packages

nuget:
  disable_publish_on_pr: true

configuration: Release

build_script: build.bat Ci

build:
  publish_nuget: true

test:
  assemblies:
    - '**\*.Tests.dll'

artifacts:
  - path: **\Prim*.nupkg

deploy:
  - provider: NuGet
    api_key:
      secure: f58g0NWO1c1HlJ13otoIyxDO+S5DJbkdBXJ+9l1th4ePTmuBcMI+DDNSmkAoK5cE
    on:
      appveyor_repo_tag: false
