#---------------------------------#
#    environment configuration    #
#---------------------------------#

# branches to build
branches:
  # whitelist
  only:
    - master
    - dev

cache:
  - packages

nuget:
  disable_publish_on_pr: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic MSBuild
build_script: build.bat Ci

#---------------------------------#
#       tests configuration       #
#---------------------------------#

test:
  assemblies:
    - test-assembly-A.dll
    - '**\*.Tests.dll'
#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: 'build\**\*.nupkg'
  - path: 'build\**\*.zip'

#---------------------------------#
#      deployment configuration   #
#---------------------------------#

deploy:
  - provider: NuGet
    api_key:
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: true
