version: 1.0.{build}

branches:
  only:
    - master
    - dev

cache:
  - packages

nuget:
  disable_publish_on_pr: true

build_script: build.bat Ci

build:
  publish_nuget: true

test:
  assemblies:
    - test-assembly-A.dll
    - '**\*.Tests.dll'

artifacts:
  - path: '**\Prim.nupkg'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "2.2.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

deploy:
  - provider: NuGet
    api_key:
      secure: 8BQmcR1hP9MoxvrmXJKMtlRyX6LI36H9ZTU8fSEetvzMGCl1PUlXKZRUGq+GVMja
    on:
      appveyor_repo_tag: false
