version: 1.0.{build}

branches:
  only:
    - master
    - dev

cache:
  - packages

nuget:
  disable_publish_on_pr: true

build_script: build.bat Ci

build:
  publish_nuget: true

test:
  assemblies:
    - test-assembly-A.dll
    - '**\*.Tests.dll'

artifacts:
  - path: '**\*.nupkg'

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

deploy:
  - provider: NuGet
    api_key:
      secure: f58g0NWO1c1HlJ13otoIyxDO+S5DJbkdBXJ+9l1th4ePTmuBcMI+DDNSmkAoK5cE
    on:
      appveyor_repo_tag: false
